parameters:
#    ml_service.example.class: Ml\ServiceBundle\Example

services:
#    ml_service.example:
#        class: %ml_service.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
