<?php

namespace Ml\GroupBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GrouppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrouppRepository extends EntityRepository
{
}
