<?php

namespace Ml\GroupBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupUserRepository extends EntityRepository
{
}
