<?php

namespace Ml\ServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarpoolingUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarpoolingUserRepository extends EntityRepository
{
}
