<?php

namespace Ml\ServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CouchSurfingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouchSurfingRepository extends EntityRepository
{
}
