<?php

namespace Ml\PrestationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestationRepository extends EntityRepository
{
}
